export enum CategoryEnum {
    'CATEGORY_HAMBURGER' = 'CATEGORY_HAMBURGER',
    'CATEGORY_ACCOMPANIMENT' = 'CATEGORY_ACCOMPANIMENT',
    'CATEGORY_DRINK' = 'CATEGORY_DRINK',
    'CATEGORY_DESSERT' = 'CATEGORY_DESSERT'
}