# Use the official PostgreSQL image from Docker Hub
FROM postgres:latest

# Define environment variables
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=tech-challenge

# Expose the PostgreSQL port
EXPOSE 5432
